# Generated by Django 5.0.6 on 2024-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.EmailField(blank=True, default=0, max_length=254, null=True),
        ),
    ]
