# Generated by Django 5.0.6 on 2024-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_signup_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='otp',
            field=models.CharField(blank=True, default=0, max_length=6, null=True),
        ),
    ]
